repo_name: ReEnAct on Github
repo_url: https://github.com/rl-institut/ReEnAct_web
site_name: ReEnAct Documentation
site_url: http://127.0.0.1:8000/

nav:
  - ReEnAct:
    - Project Description: index.md
  - Energy Planner:
    - Installation and Setup: ep_setup.md
    - Management: ep_management.md
  - Energy System Model:
      - Model Structure: esm_structure.md
      - Installation and Setup: esm_setup.md
      - Usage: esm_usage.md


plugins:
  - search:
      lang:
        - en
        - de
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - toc.follow
    - search.highlight
    - search.suggestions
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - docs/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.smartsymbols:
      arrows: True
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
