# Generated by Django 5.0.9 on 2025-09-08 09:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reenact", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaunaFloraHabitat",
        ),
        migrations.AlterField(
            model_name="generatorbiomass",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
