# Generated by Django 5.0.9 on 2025-09-08 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reenact", "0002_delete_faunaflorahabitat_alter_generatorbiomass_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatorpvground",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="generatorpvroof",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="generatorwind",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="generatorwind15a",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="generatorwind25a",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
