# Generated by Django 5.0.9 on 2025-09-08 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reenact", "0003_alter_generatorpvground_geom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powergrid",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
